version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      crates:
        patterns:
          - "*"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/xtask" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      crates:
        patterns:
          - "*"
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/webui"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      crates:
        patterns:
          - "*"
  - package-ecosystem: "github-actions" # See documentation for possible values
     directory: "/" # Location of package manifests
     schedule:
       interval: "daily"
