# Copyright 2025 Magic Mount-rs Authors
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
fs_extra = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
toml = "0.9.10"
zip = "7.0.0"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
hex = "0.4.3"
rand_core = { version = "0.9.3", features = ["getrandom"], default-features = false }
sha2 = "0.10.9"
base64 = "0.22.1"
