name: lints-check
on:
  push:
    branches: ["master"]
    paths:
      - 'src/**'
      - 'Cargo.*'
      - 'webui/**'
      - 'build.rs'
      - 'module/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'webui/**'
      - 'src/**'
      - 'Cargo.*'
      - 'build.rs'
      - 'module/**'
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: aarch64-linux-android
          components: rustfmt, clippy
      - name: Clippy code
        run: cargo clippy --all-targets -- -D warnings
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: aarch64-linux-android
          components: rustfmt, clippy
      - name: Check style
        run: cargo fmt --message-format=json --all
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC2086 -e SC2115
        with:
          format: json
