name: lints-check
on:
  push:
    branches: ["master"]
    paths:
      - 'src/**'
      - 'Cargo.*'
      - 'webui/**'
      - 'build.rs'
      - 'module/**'
  pull_request:
    branches: ["master"]
    paths:
      - 'webui/**'
      - 'src/**'
      - 'Cargo.*'
      - 'build.rs'
      - 'module/**'
env:
  CARGO_TERM_COLOR: always
jobs:
  lints-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: aarch64-linux-android
          components: rustfmt, clippy
      - name: Format codes
        uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: ./
      - name: Clippy code
        run: cargo clippy --all-targets -- -D warnings
  webui-check:
    uses: so1ve/workflows/.github/workflows/conventional-ci.yml@v1
    with:
      skip-test: true
      working-directory: webui
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          format: json
